const aInfoSpain = [];

aInfoSpain.push( { nombre: "Camila", salario: 850 });
aInfoSpain.push( { nombre: "Nath", salario: 1580 });
aInfoSpain.push( { nombre: "Luisa", salario: 1800 });
aInfoSpain.push( { nombre: "Laura", salario: 1000 });
aInfoSpain.push( { nombre: "Daniela", salario: 2200 });
aInfoSpain.push( { nombre: "Esperancita", salario: 700 });
aInfoSpain.push( { nombre: "Carla", salario: 1100 });
aInfoSpain.push( { nombre: "Julia", salario: 900 });
aInfoSpain.push( { nombre: "Rosa", salario: 1000 });
aInfoSpain.push( { nombre: "Angélica", salario: 1400 });
aInfoSpain.push( { nombre: "Tatiana", salario: 1450 });
aInfoSpain.push( { nombre: "Lorena", salario: 1600 });
aInfoSpain.push( { nombre: "Carolina", salario: 1900 });
aInfoSpain.push( { nombre: "Fernanda", salario: 2600 });
aInfoSpain.push( { nombre: "Nora", salario: 1950 });
aInfoSpain.push( { nombre: "Pedro", salario: 2300900 });
aInfoSpain.push( { nombre: "Guillermo", salario: 1300 });
aInfoSpain.push( { nombre: "Antonio", salario: 1750 });
aInfoSpain.push( { nombre: "Adriana", salario: 1650 });
aInfoSpain.push( { nombre: "Muriel", salario: 2800 });
aInfoSpain.push( { nombre: "Miguel", salario: 1700 });